[package]
name = "rustpix"
version = "0.1.2"
edition = "2021"

[dependencies]
image = "0.24"  # For image processing (including WebP)
uuid = { version = "1", features = ["v4"] }  # For generating UUIDs
rayon = "1.5"  # For parallel processing
webp = "0.3.0" # For handling webp output resolution