[package]
name = "rustpix"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"  # For image processing (including WebP)
uuid = { version = "1", features = ["v4"] }  # For generating UUIDs
rayon = "1.5"  # For parallel processing (optional)
walkdir = "2.3"  # For handling file patterns (optional)
webp = "0.3.0" # For handling webp output resolution